use super::TraceEvent;

impl TraceEvent {
    pub fn label(&self) -> &'static str {
        match self {
            TraceEvent::UserPromptSubmitted { .. } => "prompt",
            TraceEvent::IntentRouted { .. } => "intent",
            TraceEvent::RouteCandidateEvaluated { .. } => "route.candidate",
            TraceEvent::RouteCompetitionSummary { .. } => "route.competition",
            TraceEvent::ContextTokenBreakdown { .. } => "context.tokens",
            TraceEvent::ResourcePolicySelected { .. } => "resource.policy",
            TraceEvent::TaskContextBuilt { .. } => "task.context",
            TraceEvent::TaskContractMaterialized { .. } => "task.contract",
            TraceEvent::ContextPackMaterialized { .. } => "context.pack",
            TraceEvent::ImplementationIntentRecorded { .. } => "implementation.intent",
            TraceEvent::WorkflowJudgmentCompleted { .. } => "workflow.judgment",
            TraceEvent::WorkflowPlanProgress { .. } => "workflow.plan",
            TraceEvent::WorkflowLearningAdjusted { .. } => "workflow.learning",
            TraceEvent::StageValidationCompleted { .. } => "stage.validation",
            TraceEvent::ReflectionPassCompleted { .. } => "reflection.pass",
            TraceEvent::SessionGoalUpdated { .. } => "goal",
            TraceEvent::GoalDriftDetected { .. } => "goal.drift",
            TraceEvent::DestructiveScopeChecked { .. } => "destructive.scope",
            TraceEvent::WorkflowRouted { .. } => "workflow.route",
            TraceEvent::WorkflowCompleted { .. } => "workflow.done",
            TraceEvent::WorkflowFallback { .. } => "workflow.fallback",
            TraceEvent::AgentLoopStepEvaluated { .. } => "agent.loop",
            TraceEvent::StopCheckEvaluated { .. } => "stop.check",
            TraceEvent::WorkflowContractActivation { .. } => "workflow.contract",
            TraceEvent::RiskSignalAssessed { .. } => "risk.signal",
            TraceEvent::AdaptiveWorkflowTriggered { .. } => "workflow.trigger",
            TraceEvent::MemorySnapshotInjected { .. } => "memory.snapshot",
            TraceEvent::MemoryPrefetch { .. } => "memory.prefetch",
            TraceEvent::ActiveMemoryEvaluated { .. } => "memory.active",
            TraceEvent::SelfEvolutionGuidanceInjected { .. } => "self_evolution.guidance",
            TraceEvent::RetrievalContextBuilt { .. } => "retrieval.context",
            TraceEvent::ContextZonesMaterialized { .. } => "context.zones",
            TraceEvent::CacheStabilitySnapshot { .. } => "cache.stability",
            TraceEvent::PromptCacheUsageRecorded { .. } => "cache.usage",
            TraceEvent::MemoryBoundaryEvaluated { .. } => "memory.boundary",
            TraceEvent::MemoryProposalPrepared { .. } => "memory.proposal",
            TraceEvent::CloseoutBackgroundStage { .. } => "closeout.background",
            TraceEvent::MemorySynced { .. } => "memory.sync",
            TraceEvent::ContextCompacted { .. } => "context.compact",
            TraceEvent::RuntimeDietReport { .. } => "runtime.diet",
            TraceEvent::ApiRequestStarted { .. } => "api.start",
            TraceEvent::ProviderMessageSequenceNormalized { .. } => "provider.protocol",
            TraceEvent::ProviderToolCallRepairApplied { .. } => "provider.tool_repair",
            TraceEvent::StreamingToolExecutionShadow { .. } => "streaming.tool.shadow",
            TraceEvent::ApiRequestCompleted { .. } => "api.done",
            TraceEvent::ProviderRequestStarted { .. } => "provider.request.start",
            TraceEvent::ProviderRequestRetrying { .. } => "provider.request.retry",
            TraceEvent::ProviderRequestSlowWarning { .. } => "provider.request.slow",
            TraceEvent::ProviderRequestCompleted { .. } => "provider.request.done",
            TraceEvent::ProviderRequestTimeout { .. } => "provider.request.timeout",
            TraceEvent::ProviderRequestCancelled { .. } => "provider.request.cancelled",
            TraceEvent::ToolStarted { .. } => "tool.start",
            TraceEvent::ActionDecisionEvaluated { .. } => "action.decision",
            TraceEvent::CandidateActionsEvaluated { .. } => "action.candidates",
            TraceEvent::ActionReviewed { .. } => "action.review",
            TraceEvent::MemoryRecallScored { .. } => "memory.recall",
            TraceEvent::MemoryWriteScored { .. } => "memory.write",
            TraceEvent::MemoryKeepScored { .. } => "memory.keep",
            TraceEvent::PermissionRequested { .. } => "permission.request",
            TraceEvent::PermissionResolved { .. } => "permission.resolve",
            TraceEvent::ToolCompleted { .. } => "tool.done",
            TraceEvent::ToolObservationRecorded { .. } => "tool.observation",
            TraceEvent::HookCompleted { .. } => "hook.done",
            TraceEvent::SubagentStarted { .. } => "subagent.start",
            TraceEvent::SubagentCompleted { .. } => "subagent.done",
            TraceEvent::VerificationCompleted { .. } => "verify.done",
            TraceEvent::RequiredValidationHeartbeat { .. } => "required_validation.heartbeat",
            TraceEvent::AcceptanceReviewCompleted { .. } => "acceptance.review",
            TraceEvent::GuidedDebuggingCompleted { .. } => "guided.debug",
            TraceEvent::RecoveryApplied { .. } => "recovery",
            TraceEvent::RecoveryPlan { .. } => "recovery.plan",
            TraceEvent::McpResourceAccessed { .. } => "mcp.resource",
            TraceEvent::RemoteBridgeAction { .. } => "remote.bridge",
            TraceEvent::AssistantResponded { .. } => "assistant",
            TraceEvent::CompletionContractEvaluated { .. } => "completion.contract",
            TraceEvent::FinalCloseoutPrepared { .. } => "closeout",
            TraceEvent::ExecutionReportPrepared { .. } => "execution.report",
            TraceEvent::Error { .. } => "error",
        }
    }
}
